branches:
  only:
    - "master"

language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - mkdir -p testinstall/bin
  - ./i.sh `pwd`/testinstall

script:
  - test -x testinstall/bin/cli-dom
  - test $(testinstall/bin/cli-dom '//title' 'http://github.com/' | grep -c .) -gt 0
  - phpunit
