branches:
  only:
    - "master"

language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - wget -O i.sh 'https://raw.githubusercontent.com/Ejz/DOM/master/i.sh'
  - chmod a+x i.sh
  - mkdir bin
  - ./i.sh `pwd`/bin

script: phpunit
