#!/usr/bin/env php
<?php

define('ROOT', __DIR__);
require(ROOT . '/vendor/autoload.php');

use Ejz\DOM;

$opts = getopts(array(
    'm' => false, 'multiline' => false,
    'f' => false, 'format' => false,
    'd' => true, 'delimiter' => true,
    'r' => true, 'replace' => true,
    'limit' => true
));

if($opts === array()) goto help;

@ $MULTILINE = ($opts['m'] or @ $opts['multiline']);
@ $FORMAT = ($opts['f'] or @ $opts['format']);
@ ($DELIMITER = $opts['d']) or @ ($DELIMITER = $opts['delimiter']);
$DELIMITER = $DELIMITER ? $DELIMITER : ',';
@ ($REPLACE = $opts['r']) or @ ($REPLACE = $opts['replace']);
@ $LIMIT = is_numeric($opts['limit']) ? intval($opts['limit']) : null;
$URL = $opts[max(array_keys($opts))];
$XPATH = array();
for($i = 1; $i < max(array_keys($opts)); $i++)
    $XPATH[] = $opts[$i];

if(!$XPATH) goto help;

if($REPLACE and count($XPATH) > 1) {
    echo "If you use replace, you should use just one search XPATH\n";
    exit(1);
}

if($URL === '-') {
    $handle = STDIN;
    $buffer = array();
    if($handle and ftell($handle) === 0)
        while(!feof($handle))
            $buffer[] = fread($handle, 1024 * 1024);
    $content = implode('', $buffer);
} else @ $content = file_get_contents($URL);

if($MULTILINE) $content = nsplit($content);
else $content = array($content);

foreach($content as $_content):
    $dom = new DOM($_content, $FORMAT);
    if($REPLACE) {
        @ $_ = $dom -> replace($XPATHS[0], $LIMIT, $REPLACE);
        echo $_, "\n";
        continue;
    }
    $found = array();
    foreach($XPATH as $xpath)
        @ $found[] = $dom -> find($xpath, $LIMIT);
    $max = max(array_map('count', $found));
    for($i = 0; $i < $max; $i++) {
        foreach($found as $elem) echo @ $elem[$i], ($i < $max - 1 ? $DELIMITER : '');
        echo "\n";
    }
endforeach;

exit(0);

help:

echo "Usage: cli-dom [ FLAGS ] [ OPTIONS ] [ LIMIT ] XPATH URL\n";
echo "FLAGS: [ -m | --multiline ] [ -f | --format ]\n";
echo "OPTIONS: [ -d DELIMITER | --delimiter DELIMITER ] [ -r XPATH | --replace XPATH ]\n";
echo "LIMIT: [ --limit N ]\n";

exit(1);
