#!/usr/bin/env php
<?php

define('ROOT', __DIR__);
require(ROOT . '/vendor/autoload.php');

use Ejz\DOM;

$opts = getopts(array(
    'm' => false, 'multiline' => false,
    'f' => false, 'format' => false,
    'n' => false, 'no-empty' => false,
    'd' => true, 'delimiter' => true,
    'r' => true, 'replace' => true,
    'l' => true, 'limit' => true,
    'i' => true, 'index' => true,
));

if($opts === array()) goto help;
$LIMIT = ''; $INDEX = ''; $REPLACE = null;

@ ($MULTILINE = $opts['m']) or @ ($MULTILINE = $opts['multiline']);
@ ($FORMAT = $opts['f']) or @ ($FORMAT = $opts['format']);
@ ($NO_EMPTY = $opts['n']) or @ ($NO_EMPTY = $opts['no-empty']);
if(isset($opts['r']) and is_string($opts['r']))
    $REPLACE = $opts['r'];
if(isset($opts['replace']) and is_string($opts['replace']))
    $REPLACE = $opts['replace'];
if(isset($opts['d']) and is_string($opts['d']))
    $DELIMITER = $opts['d'];
if(isset($opts['delimiter']) and is_string($opts['delimiter']))
    $DELIMITER = $opts['delimiter'];
if(isset($opts['l']) and is_numeric($opts['l']))
    $LIMIT = intval($opts['l']);
if(isset($opts['limit']) and is_numeric($opts['limit']))
    $LIMIT = intval($opts['limit']);
if(isset($opts['i']) and is_numeric($opts['i']))
    $INDEX = intval($opts['i']);
if(isset($opts['index']) and is_numeric($opts['index']))
    $INDEX = intval($opts['index']);

@ $DELIMITER = $DELIMITER ? $DELIMITER : ',';
if(is_numeric($INDEX) and !is_numeric($LIMIT)) $LIMIT = 1;
if(is_numeric($LIMIT) and !is_numeric($INDEX)) $INDEX = 0;
$URL = $opts[max(array_keys($opts))];
$XPATH = array();
for($i = 1; $i < max(array_keys($opts)); $i++)
    $XPATH[] = $opts[$i];

if(!$XPATH) goto help;
if(is_string($REPLACE) and count($XPATH) > 1) goto help;

if($URL === '-') {
    $handle = STDIN;
    $buffer = array();
    if($handle and ftell($handle) === 0)
        while(!feof($handle))
            $buffer[] = fread($handle, 1024 * 1024);
    $content = implode('', $buffer);
} else @ $content = file_get_contents($URL);

if($MULTILINE) $content = nsplit($content);
else $content = array($content);

foreach($content as $_content):
    $dom = new DOM($_content, array('format' => $FORMAT, 'no-empty' => $NO_EMPTY));
    if(is_string($REPLACE)) {
        @ $_ = $dom -> replace($XPATH[0], ($LIMIT ? "{$INDEX}-{$LIMIT}" : $INDEX), $REPLACE);
        echo $_, "\n";
        continue;
    }
    // continue;
    $found = array();
    foreach($XPATH as $xpath) {
        @ $_ = $dom -> find($xpath);
        if(!is_array($_)) $found[] = array($_);
        elseif(!is_numeric($INDEX) and !is_numeric($LIMIT))
            $found[] = $_;
        else $found[] = array_slice($_, $INDEX, $LIMIT);
    }
    $max = max(array_map('count', $found));
    if(is_numeric($LIMIT) and $max > $LIMIT) $max = $LIMIT;
    for($i = 0; $i < $max; $i++) {
        for($j = 0; $j < count($found); $j++)
            echo @ $found[$j][$i], ($j < count($found) - 1 ? $DELIMITER : '');
        echo "\n";
    }
endforeach;

exit(0);

help:

ob_start();
echo "Usage: cli-dom [ FLAGS ] [ OPTIONS ] XPATHS URL\n";
echo "FLAGS:\n";
echo "    [ -m | --multiline ] - input is said to be multiline\n";
echo "    [ -f | --format ] - prettify output\n";
echo "    [ -n | --no-empty ] - ignore text nodes that contain only whitespace\n";
echo "OPTIONS:\n";
echo "    [ -d DELIMITER | --delimiter DELIMITER ] - delimiter of results in output\n";
echo "    [ -i INDEX | --index INDEX ] - output from INDEX item\n";
echo "    [ -l LIMIT | --limit LIMIT ] - limit items in output starting with LIMIT\n";
echo "    [ -r XPATH | --replace XPATH ] - perform replace operation\n";
$ob = ob_get_clean();
fwrite(STDERR, $ob);

exit(1);
