#!/usr/bin/env php
<?php

define('ROOT', __DIR__);
require(ROOT . '/vendor/autoload.php');

use Ejz\DOM;

@ $args = $_SERVER['argv'] ? $_SERVER['argv'] : array();
array_shift($args);
if(!$args) {
    echo "Invalid argument \$xpath", chr(10);
    exit(1);
}

if(isset($args[0]) and $args[0] === '-m') {
    array_shift($args);
    $multiline = true;
} else $multiline = false;

if(isset($args[0]) and $args[0] === '-f') {
    array_shift($args);
    $format = true;
} else $format = false;

if(!$args) {
    echo "Invalid argument \$xpath", chr(10);
    exit(1);
}

$handle = STDIN;
$buffer = array();
if($handle and ftell($handle) === 0)
    while(!feof($handle))
        $buffer[] = fread($handle, 1024 * 1024);
$buffer = implode('', $buffer);

if(!$buffer) exit(1);

if($multiline) $buffer = nsplit($buffer);
else $buffer = array($buffer);

// -d parameter
$_ = array();
$d = false;
foreach($args as $arg)
    if($arg === '-d') {
        $d = true;
    } elseif($d) {
        $_[] = "--delimiter={$arg}";
        $d = false;
    } else $_[] = $arg;

$args = $_;
$_args = $args;

foreach($buffer as $content):

$dom = new DOM($content, $format);
$max = 0;
$args = $_args;
array_walk($args, function(& $xpath) use($dom, & $max) {
    if(strpos($xpath, $_ = '--delimiter=') === 0) {
        $xpath = substr($xpath, strlen($_));
        return;
    }
    $elem = array();
    @ $__ = $dom -> find($xpath);
    if($__) $elem = $__;
    $xpath = $elem;
    if(count($xpath) > $max) $max = count($xpath);
});

for($i = 0; $i < $max; $i++) {
    $space = false;
    foreach($args as $arg) {
        if(!is_array($arg)) echo $arg;
        elseif(isset($arg[$i])) {
            if($space) echo " ";
            echo $arg[$i];
            $space = true;
            continue;
        }
        $space = false;
    }
    echo chr(10);
}

endforeach;
